### ISSUE TITLE
String based datatypes to be explained in YANG files

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#12]
Either ImplementationCommonDatatypes or IetfYangTypes to be use in UML. Types not been translated into String during UML2YANG translation, but to maintained with the initial names. YANG representation of ImplementationCommonDatatypes or IetfYangTypes to be generated and to be imported into YANG file of tech.spec. Interface/Profile yang.

**Comment by openBackhaul** [comment]
ImplementationCommonDataTypes | IetfYangTypes (UML) | IetfYangTypes (YANG)
-- | -- | --
DateTime | DateAndTime | date-and-time
Uuid | Uuid | uuid
MacAddress | MacAddress | mac-address
  |   |  
ImplementationCommonDataTypes | IetfInetTypes | IetfInetTypes
Ipv4Address | Ipv4Address | ipv4-address

**Comment by demx8as6** [comment]
generated example for yang:date-and-time - pyang validation ok: 2019-11-10

    leaf time-stamp {
      type yang:date-and-time;

**Comment by demx8as6** [comment]
generated example for yang:uuid - pyang validation ok: 2019-11-10    

```
leaf object-id-ref {
      type yang:uuid;
      config false;
      description
        "ID of the affected MW_AirInterface_Pac";
    }
```

**Comment by openBackhaul** [comment]
IETF Types manually added to the YANG file produced by UML2YANG tool.
