### ISSUE TITLE
PMD kind attributes as references instead of containers?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#13]
The following PMD kind attributes are currently defined as containers (each holding the full set of children):
- _fixed-pmd-kind_
-  _auto-negotiation-pmd-list_
-  _pmd-kind-cur_

I would have expected the attributes to be references (_leafref_) to a PMD name in the _supported-pmd-kind-list_.

**Comment by openBackhaul** [comment]
All associations (references in e.g. Configuration) on existing instances of classes, which are describing capabilities, shall be of aggregation type shared instead of none.

**Comment by openBackhaul** [comment]
Associations for
- fixed-pmd-kind
- auto-negotiation-pmd-list
- pmd-kind-cur
have been changed to be of aggregation type "shared".
