### ISSUE TITLE
PmdKind: pmdName not unique?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#14]
The description (comment) for the _pmdName_ attribute of the _PmdKind_ class (Yang: _pmd-kind/pmd-name_) defines a list of PMD names to be used as values.

In my understanding connectors for some of the PMDs can be operated with various bit rates (speed) and/or duplex modes. That is, the _supported-pmd-kind-list_ can have multiple entries for such PMDs.

As a consequence the _pmd-name_ attribute of the _pmd-kind_ grouping cannot be used as key.

Is this view correct?

**Comment by rservadio** [comment]
I add a comment to track what was said in the call.
pmdName is of type string.
In the yang module the description lists all the available values.
The list does not allow the distinction between the same name but with a different duplex option (FullDuplex or HalfDuplex).
The proposal is to add the suffix to the name:
- "-FD" for FullDuplex
- "-HD" for HalfDuplex

**Comment by openBackhaul** [comment]
The comment of the PmdKind:pmdName attribute has been amended with the following formulation: "Some PMDs are distinguishing Full Duplex and Half Duplex operation. '_FD' and '_HD' are to be attached to the respective PMD name accordingly."

**Comment by openBackhaul** [comment]
> In my understanding connectors for some of the PMDs can be operated with various bit rates (speed) and/or duplex modes.
A PMD has always just one speed (if a 1000BASE-T would be operated with 100Mbit/s, it would be a 100BASE-T).
The Duplex operation might differ, that's correct.
Corresponding extentions to the name of the PMD have been defined for being able to use the pmdName attribute as only key attribute.
