### ISSUE TITLE
Capability do not provide for declaring isolation support

### ISSUE THREAD

**Issue by niloda** [openBackhaul/wireInterface#15]
Some devices do not implement the separation of PHY from higher network levels. The current model provides an attribute (isolationIsOn) in WireInterfaceConfiguration to enable and disable isolation but in WireInterfaceCapability an attribute is not provided to declare if the device implements this function.

The proposed solution:
Adding the Boolean isolationIsAvail attribute to WireInterfaceCapability

**Comment by openBackhaul** [comment]
WireInterfaceCapability::isolationIsAvail attribute with comment "1 = Separation of the PHY from higher network layers is supported by the device. Maintenance feature. Source: 802.3." added.
