### ISSUE TITLE
auto-negotiation-pmd-list with inconsistent min-elements

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#17]
The _auto-negotiation-pmd-list_ (leaf) list has a constraint `min-elements 1` which does not match the description:
> If (autoPmdNegotiationIsOn==1) AND (autoNegotiationPmdSelectionIsAvail==1), this list defines the selection of PMDs the automated negotiation process is allowed to choose from. If no entry, the automated negotiation process is allowed to choose from all available PMDs.

The description implies that the list is optional. If this is true the constraint should be removed.

**Comment by openBackhaul** [comment]
Multiplicity of _autoNegotiationPmdList has been changed from [1..*] to [*].
