### ISSUE TITLE
objectClass of CurrentPerformace and HistoricalPerformance data type is not needed

### ISSUE THREAD

**Issue by niloda** [openBackhaul/wireInterface#21]
see description provided for airInterface model

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 28th of July 2021:**
Just closing the issue

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul call on 28th of July 2021:**
Issue just to be closed without further action.
