### ISSUE TITLE
time-of-latest-change: wrong type

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#26]
The following time stamps have type string but should have type `yang:date-and-time`:

- `wire-interface-current-problems/time-of-latest-change`
- `wire-interface-historical-performances/time-of-latest-change`

**Comment by openBackhaul** [comment]
In the UML it's fine.
In the YANG reference it's also fine (no change required).

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 28th of July 2021:**
Just closing the issue

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul call on 28th of July 2021:**
Issue just to be closed without further action.
