### ISSUE TITLE
transceiverIsOnList cannot be addressed

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#27]
transceiverIsOnList is of datatype Boolean[*] (Array of Boolean).

Unfortunately, list attributes cannot be addressed neither for reading nor for writing.
So, the entire Array cannot be addressed.

Because it is a primitive datatype, the instances in the Array do not have a key attribute, which could be addressed by value.
So, the elements inside the Array can also not be addressed.

As a consequence, any value inside the Array can only be addressed by reading and writing the entire Configuration Class.

Proposal:
Changing the primitive Boolean into a composed datatype combing an instance number (e.g. transceiverNumber : Integer) with the actual configuration parameter (e.g. isOn : Boolean).

**Comment by openBackhaul** [comment]
Covered by the decision made in [issue#28](https://github.com/openBackhaul/wireInterface/issues/28).

**Comment by demx8as6** [comment]
considered as duplicated of #28
