### ISSUE TITLE
wavelengthList cannot be addressed

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#28]
wavelengthList is of datatype Integer[0..3] (Array of Integer).

Unfortunately, list attributes cannot be addressed neither for reading nor for writing.
So, the entire Array cannot be addressed.

Because it is a primitive datatype, the instances in the Array do not have a key attribute, which could be addressed by value.
So, the elements inside the Array can also not be addressed.

As a consequence, any value inside the Array can only be addressed by reading and writing the entire Configuration Class.

Proposal:
Changing the primitive Integer into a composed datatype combing an instance number (e.g. transceiverNumber : Integer) with the actual configuration parameter (e.g. wavelength : Integer).

**Comment by openBackhaul** [comment]
**Decision on the 5G-xhaul call on 4th of August 2021:**
- Creating a new WireInterfaceConfiguration::transceiverConfigurationList : transceiverConfigurationType [1..10] attribute. (Be aware of the changed multiplicity, which leads to at least one transmitter being represented).
- Creating a new transceiverConfigurationType datatype.
- Creating a new transceiverConfigurationType::transceiverIndex : Int8 key attribute.
- Creating a new transceiverConfigurationType::transceiverIsOn : Boolean = false attribute with comment == "Source: 802.3 45.2.1.8 PMD transmit disable register (Register 1.9). true = Activation of the individual transmitter and receiver (e.g. laser) of the PHY." 
- Creating a new transceiverConfigurationType::wavelength : Int32 = -1 attribute with unit == "pm" and comment == "Source: SFF-8690. Wavelength of the signal of laser in pico meter."
- Deleting the WireInterfaceConfiguration::transceiverIsOnList attribute.
- Deleting the WireInterfaceConfiguration::wavelengthList attribute.

**Comment by DanielaSpreafico** [comment]
A question: to address a common transceiver , is this the first instance (with transceiverIndex = 1) ?

**Comment by demx8as6** [comment]
Answer to the question:
the model provides individual switches for transceivers - in this sense there is no "common transceiver" and no specific behavior described related to "common transceivers".

**Comment by openBackhaul** [comment]
Solved with WireInterface_2.0.0-tsp.220314.1810 release.
