### ISSUE TITLE
receiveSignalIsDetectedList is unordered

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#29]
receiveSignalIsDetectedList is of datatype Boolean[0..11] (Array of Boolean).

Unfortunately, content of leaf list attributes is unordered in YANG.
So, there is no way for concluding from one of the Boolean statements on a concrete signal.
As a consequence, the given information is useless.

Proposal:
Changing the primitive Boolean into a composed datatype combing an instance number (e.g. receiverNumber : Integer) with the actual status value (e.g. isUp : Boolean).

**Comment by openBackhaul** [comment]
Covered by the decision made in [issue#30](https://github.com/openBackhaul/wireInterface/issues/30).

**Comment by demx8as6** [comment]
considered as duplicate - #30
