### ISSUE TITLE
PmdKind: Default values

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#3]
The default value for the _pmdName_ attribute in the _Type_ column of the Word document differ from the one in the _Description_ column.

The default value for the _speed_ attribute refers to "PMP".

**Comment by openBackhaul** [comment]
Default value of pmdName attribute corrected to "NOT_YET_DEFINED".
Default value of speed attribute corrected to "NOT_YET_DEFINED".
Comment of speed attribute complemented by "or NOT_YET_DEFINED".
Many thanks for commenting!

**Comment by openBackhaul** [comment]
Default value of pmdName attribute had to be deleted, because it's a key attribute.
