### ISSUE TITLE
autoNegotiationPmdList cannot be addressed

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#32]
autoNegotiationPmdList translates to something like an Array of Strings (which has values that equal entries into the key attribute of the supportedPmdKindList).

Unfortunately, Array attributes cannot be addressed neither for reading nor for writing.
So, the entire Array cannot be addressed.

Because it is a list of a primitive datatype, the instances in the Array do not have any key attribute (that the values of the String equal values of a key attribute in the referenced list, doesn't play a role), which could be addressed by value.
So, the elements inside the Array can also not be addressed.

As a consequence, any value inside the Array can only be addressed by reading and writing the entire Configuration Class.

Proposal:
Changing the simple leaf-ref into a composed datatype combing an instance number (e.g. supportedPmdKindNumber : Integer) with the leaf-ref to the entry in the supportedPmdKindList.

**Comment by demx8as6** [comment]
Just an test example to show the yang mechanics of  a selection of values in configuration (rw) from a list within capabilities (ro)

[ms-test.tree.txt](https://github.com/openBackhaul/wireInterface/files/6853816/ms-test.tree.txt)
[ms-test.yang.txt](https://github.com/openBackhaul/wireInterface/files/6853944/ms-test.yang.txt)

**Comment by alexandrustancu** [comment]
Also a test data xml:

[ms-test.xml.txt](https://github.com/openBackhaul/wireInterface/files/6853960/ms-test.xml.txt)

**Comment by openBackhaul** [comment]
**Decision at the 5G-xhaul call on 18th of August:**
The modelling of the function shall stay as it currently is, but the comment shall be changed to be formulated like this:
"If (autoPmdNegotiationIsOn==1) AND (autoNegotiationPmdSelectionIsAvail==1), this list defines the selection of PMDs the automated negotiation process is allowed to choose from. If the device would not allow excluding PMDs, which are supported by the device, from the process of auto negotiation, the list shall be empty (which means that the attribute does not appear). If the device would allow excluding PMDs, all supported PMDs shall be listed as a default. (On the RESTCONF interface, this attribute has to be address by ?fields filter.)"

**Comment by openBackhaul** [comment]
Solved with WireInterface_2.0.0-tsp.220314.1810 release.
