### ISSUE TITLE
Replacing restart-pmd-negotiation-is-on by RPC

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wireInterface#35]
restart-pmd-negotiation-is-on is not a configurable attribute (which would have an administrative and an operational state), but initiation of a negotiation operation on the device.

Potentially, it would be better to replace the attribute by an RPC definition.

**Comment by demx8as6** [comment]
RPC seams to be the better operation for such case.
we may need to have similar cases in other interfaces (clear-something, ....)

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 18th of August 2021:**
- create WireInterfaceOperations Interface with comment: "Group of operations, which are effective on an already existing WireInterface."
- create a WireInterfaceOperations::restartPmdNegotiation( in _affectedWireInterface:LogicalTerminationPoint ) operation 
  - with comment: "Restarts the PMD auto negotiation process on the referenced WireInterface. The following error-message is to be send, if the operation would fail: #[onf:Referenced object is invalid.]#, if the referenced LogicalTerminationPoint does not exist or does not belong to the Wire layer." 
  - and isOperationIdempotent==true isAtomic==true.
- delete existing WireInterfaceConfiguration::restartPmdNegotiationIsOn : Boolean = false attribute

**Comment by PrathibaJee** [comment]
Since the UML2YANG tool doesn’t  have the capability to translate the UML artifacts “idempotent” and “atomic” into corresponding Yang modelling , we have to complement it in the comment(description) field of the operation.

**Comment by openBackhaul** [comment]
**Decision at the 5G-xhaul call on 18th of August 2021:**
- create WireInterfaceOperations Interface with comment: "Group of operations, which are effective on an already existing WireInterface."
- create a WireInterfaceOperations::restartPmdNegotiation( in _affectedWireInterface:LogicalTerminationPoint ) operation 
  - with comment: "Restarts the PMD auto negotiation process on the referenced WireInterface. The following error-message is to be send, if the operation would fail: #[onf:Referenced object is invalid.]#, if the referenced LogicalTerminationPoint does not exist or does not belong to the Wire layer." 
  - and isAtomic==true.
- delete existing WireInterfaceConfiguration::restartPmdNegotiationIsOn : Boolean = false attribute

**Comment by openBackhaul** [comment]
Solved with WireInterface_2.0.0-tsp.220314.1810 release.
