### ISSUE TITLE
2.5GBbit/s interface should be supported 

### ISSUE THREAD

**Issue by niloda** [openBackhaul/wireInterface#37]
Nowadays many SFP module manufacturers have 2500Base-X type devices in their portfolios that work at 2.5Gbps speed, and many switch / router manufacturers have products with 2500Base-T interfaces in their catalog. In some specific use cases, they are also used by MW devices, so the model should support these types.

Proposal:
- add the types 2500BASE-T and 2500BASE-X to the `pmd-name` object attribute of the `pmd-kind` grouping
- add  the value '2.5GBbit/s' to the `speed` attribute comment of `pmd-kind` grouping 
- add the 2500BASE-T and 2500BASE-X types to the `description` of the module

As a further improvement, the `pmd-name` and `pmd-kind` attributes could be more strongly typed by transforming them from string to identity.

**Comment by openBackhaul** [comment]
**Decision on the 5G-xhaul call on 10th of November 2021:**
- Changing the comment of the pmd-kind::pmd-name attribute from
"To be chosen from the following list of PMD names according to IEEE 802.3 '10BASE5', ... '1000BASE-T', '10GBASE-X', ..."
to "To be chosen from the following list of PMD names according to IEEE 802.3 '10BASE5', ... '1000BASE-T', **'2500BASE-T', '2500BASE-X',** '10GBASE-X', ..."
- Changing the comment of the pmd-kind::speed attribute from "Line speed of the PMD. Value to be chosen from '2Mbit/s', ... , '1000Mbit/s', '10Gbit/s', ..." to "Line speed of the PMD. Value to be chosen from '2Mbit/s', ... , '1000Mbit/s', **'2500Mbit/s',** '10Gbit/s', ..."
- Changing the comment at the root element from "This model is for vendor agnostic management of Ethernet PHY interfaces. Supported: '10BASE5',..., '1000BASE-T', '10GBASE-X', ..." to "This model is for vendor agnostic management of Ethernet PHY interfaces. Supported: '10BASE5',..., '1000BASE-T', **'2500BASE-T', '2500BASE-X',** '10GBASE-X', ..."

**Comment by openBackhaul** [comment]
Solved with WireInterface_2.0.0-tsp.220314.1810 release.
