### ISSUE TITLE
PmdKind: Numerical values for speed?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/wireInterface#4]
Should the _speed_ attribute not have numerical values (in Mbit/s) instead of string values? There might be other values in addition to those listed in the _Description_ column of the Word document, perhaps for CPRI.

**Comment by openBackhaul** [comment]
speed attribute is just for choosing the PMD; intend to prevent Users applying the speed attribute for calculations without thinking about the actual meaning of the value.
WireInterface is for Ethernet PHY according to 802.3 (e.g. no CPRI).
This very much restricts to the given values.
In principle, String attributes for pmdName and speed are open for future PMD definitions in 802.3, but complete coverage of potentially additionally required attributes is not assured.
Nevertheless, thanks for commenting.
